[package]
name = "helix-macros"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
description = "Proc macros for HelixQL"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
